version: '3.8'

services:
  psql:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_BD=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/django-code
    env_file:
      - ./api/.env
    depends_on:
      - psql
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  web: 
    build: ./clientFrontEnd
    ports:
      - "3000:3000"
    volumes:
      - ./clientFrontEnd:/react-code
    command: ["npm", "run", "dev"]